# Build with:
# docker build --build-arg MK="mk-2024.0-full.tar.gz" -t pcafrica/mk -f Dockerfile_hub .
# docker tag pcafrica/mk pcafrica/mk:2024.0
# Then push with:
# docker login
# docker push pcafrica/mk:latest
# docker push pcafrica/mk:2024.0


FROM ubuntu:latest AS mk_builder

MAINTAINER pasqualeclaudio.africa@polimi.it


# Define variables.
ARG MK

# Install dependencies.
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y wget curl openssh-client zip unzip \
      clang-format cppcheck doxygen graphviz


# Copy modules file.
COPY ${MK} /

# Un-tar modules.
RUN tar xvzf ${MK} -C / && \
    rm ${MK}


FROM scratch AS mk
COPY --from=mk_builder / /

ENV HOME /root

# Enable modules by default.
RUN printf "\n# mk.\n\
source /u/sw/etc/profile\n\
module load gcc-glibc\n\
module load eigen tbb" >> ${HOME}/.bashrc

# Setup for MPI.
ENV OMPI_MCA_btl_vader_single_copy_mechanism=none
ENV OMPI_ALLOW_RUN_AS_ROOT=1
ENV OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

# Set configuration variables.
USER root
WORKDIR ${HOME}
